# Generated by Django 4.0.6 on 2022-12-01 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0004_exam_exam_question_question_delete_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_question',
            name='exam_id',
        ),
        migrations.RemoveField(
            model_name='exam_question',
            name='question_id',
        ),
        migrations.AddField(
            model_name='exam_question',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='examapp.exam'),
        ),
        migrations.AddField(
            model_name='exam_question',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='examapp.question'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.DurationField(default='00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='maximum_marks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='num_questions',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question_negative_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
