# Generated by Django 4.0.6 on 2022-11-08 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examapp', '0004_exam_exam_question_question_delete_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('candidate_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('password1', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='candidate_exam_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candidate.candidate')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.exam')),
                ('question_is', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.question')),
            ],
        ),
        migrations.CreateModel(
            name='candidate_exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_attempted_questions', models.IntegerField()),
                ('num_correct_questions', models.IntegerField()),
                ('num_incorrect_questions', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candidate.candidate')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.exam')),
            ],
        ),
    ]
