# Generated by Django 4.0.6 on 2022-12-01 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_exam',
            name='candidate_id',
        ),
        migrations.RemoveField(
            model_name='candidate_exam',
            name='exam_id',
        ),
        migrations.RemoveField(
            model_name='candidate_exam_questions',
            name='candidate_id',
        ),
        migrations.RemoveField(
            model_name='candidate_exam_questions',
            name='exam_id',
        ),
        migrations.RemoveField(
            model_name='candidate_exam_questions',
            name='question_is',
        ),
        migrations.DeleteModel(
            name='candidate',
        ),
        migrations.DeleteModel(
            name='candidate_exam',
        ),
        migrations.DeleteModel(
            name='candidate_exam_questions',
        ),
    ]
