# Generated by Django 4.0.6 on 2022-12-07 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examapp', '0005_remove_exam_question_exam_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Candidate', '0002_remove_candidate_exam_candidate_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='candidate_exam_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, null=True)),
                ('marks', models.IntegerField(default=0, null=True)),
                ('is_attempted', models.BooleanField(default=False, null=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Candidate.candidate')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='examapp.exam')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='examapp.question')),
            ],
        ),
        migrations.CreateModel(
            name='candidate_exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_attempted_questions', models.IntegerField(default=0, null=True)),
                ('num_correct_questions', models.IntegerField(default=0, null=True)),
                ('num_incorrect_questions', models.IntegerField(default=0, null=True)),
                ('total_marks', models.IntegerField(default=0, null=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Candidate.candidate')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='examapp.exam')),
            ],
        ),
    ]
